on: [push, pull_request, workflow_dispatch]

jobs:
  publish-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: master
      - name: Build
        run: "mkdir -p public/zig-mesh && cd zig-mesh && zig build -Drelease-fast && cp -r ./zig-out ../public/zig-mesh"
      - name: Copy HTML & JS
        run: "cp *.html public/ && cp *.js public/ && cp zig-mesh/*.js public/zig-mesh/"
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: public
          allow_empty_commit: false
          committer_name: github-actions
          committer_email: ""
          commit_message: "Deploy browser build to GitHub Pages"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
